[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

optimizer = true
optimizer_runs = 200

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[rpc_endpoints]
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"
bsc_mainnet = "https://bsc-dataseed.binance.org/"
opbnb_testnet = "https://opbnb-testnet-rpc.bnbchain.org"
opbnb_mainnet = "https://opbnb-mainnet-rpc.bnbchain.org"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}" }
bsc_mainnet = { key = "${BSCSCAN_API_KEY}" }
opbnb_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-opbnb-testnet.bscscan.com/api" }
opbnb_mainnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-opbnb.bscscan.com/api" }
